-- Dummy Data (153 records)
INSERT INTO product (name, type, price) VALUES ('Macbook Pro', 'Laptop', 15000000);
INSERT INTO product (name, type, price) VALUES ('Head First Java', 'Book', 350000);
INSERT INTO product (name, type, price) VALUES ('Professional Apache Tomcat 8', 'Book', 30000);
INSERT INTO product (name, type, price) VALUES ('Dell XPS 15', 'Laptop', 28500000);
INSERT INTO product (name, type, price) VALUES ('HP Spectre x360', 'Laptop', 22000000);
INSERT INTO product (name, type, price) VALUES ('Lenovo ThinkPad X1 Carbon', 'Laptop', 25000000);
INSERT INTO product (name, type, price) VALUES ('Asus ROG Zephyrus G14', 'Laptop', 27000000);
INSERT INTO product (name, type, price) VALUES ('Razer Blade 15', 'Laptop', 35000000);
INSERT INTO product (name, type, price) VALUES ('Microsoft Surface Laptop 5', 'Laptop', 18500000);
INSERT INTO product (name, type, price) VALUES ('Acer Swift Go', 'Laptop', 12000000);
INSERT INTO product (name, type, price) VALUES ('Samsung Galaxy Book3', 'Laptop', 19800000);
INSERT INTO product (name, type, price) VALUES ('LG Gram 17', 'Laptop', 23500000);
INSERT INTO product (name, type, price) VALUES ('Google Pixelbook Go', 'Laptop', 9500000);
INSERT INTO product (name, type, price) VALUES ('iPhone 15 Pro', 'Smartphone', 21000000);
INSERT INTO product (name, type, price) VALUES ('Samsung Galaxy S24 Ultra', 'Smartphone', 23500000);
INSERT INTO product (name, type, price) VALUES ('Google Pixel 8', 'Smartphone', 11000000);
INSERT INTO product (name, type, price) VALUES ('OnePlus 12', 'Smartphone', 14000000);
INSERT INTO product (name, type, price) VALUES ('Xiaomi 14 Pro', 'Smartphone', 13500000);
INSERT INTO product (name, type, price) VALUES ('Oppo Find X7', 'Smartphone', 12800000);
INSERT INTO product (name, type, price) VALUES ('Asus Zenfone 10', 'Smartphone', 10500000);
INSERT INTO product (name, type, price) VALUES ('Sony Xperia 1 V', 'Smartphone', 19000000);
INSERT INTO product (name, type, price) VALUES ('Nothing Phone (2)', 'Smartphone', 8500000);
INSERT INTO product (name, type, price) VALUES ('Motorola Edge+ (2024)', 'Smartphone', 9800000);
INSERT INTO product (name, type, price) VALUES ('Clean Code', 'Book', 420000);
INSERT INTO product (name, type, price) VALUES ('The Pragmatic Programmer', 'Book', 380000);
INSERT INTO product (name, type, price) VALUES ('Designing Data-Intensive Applications', 'Book', 550000);
INSERT INTO product (name, type, price) VALUES ('Cracking the Coding Interview', 'Book', 480000);
INSERT INTO product (name, type, price) VALUES ('Introduction to Algorithms', 'Book', 750000);
INSERT INTO product (name, type, price) VALUES ('Learning Python', 'Book', 320000);
INSERT INTO product (name, type, price) VALUES ('Mastering Go', 'Book', 410000);
INSERT INTO product (name, type, price) VALUES ('The DevOps Handbook', 'Book', 390000);
INSERT INTO product (name, type, price) VALUES ('Kubernetes: Up and Running', 'Book', 430000);
INSERT INTO product (name, type, price) VALUES ('Site Reliability Engineering', 'Book', 460000);
INSERT INTO product (name, type, price) VALUES ('Logitech MX Master 3S', 'Accessory', 1500000);
INSERT INTO product (name, type, price) VALUES ('Keychron K2 Mechanical Keyboard', 'Accessory', 1300000);
INSERT INTO product (name, type, price) VALUES ('Anker USB-C Hub', 'Accessory', 650000);
INSERT INTO product (name, type, price) VALUES ('Logitech C920 Webcam', 'Accessory', 900000);
INSERT INTO product (name, type, price) VALUES ('Bose QuietComfort Headphones', 'Accessory', 4500000);
INSERT INTO product (name, type, price) VALUES ('SanDisk 1TB Extreme SSD', 'Accessory', 1800000);
INSERT INTO product (name, type, price) VALUES ('Rode NT-USB Microphone', 'Accessory', 2200000);
INSERT INTO product (name, type, price) VALUES ('Ergotron Monitor Arm', 'Accessory', 2500000);
INSERT INTO product (name, type, price) VALUES ('Apple Magic Mouse', 'Accessory', 1200000);
INSERT INTO product (name, type, price) VALUES ('WD My Passport 4TB', 'Accessory', 1600000);
INSERT INTO product (name, type, price) VALUES ('IntelliJ IDEA Ultimate (1 Year)', 'Software', 5200000);
INSERT INTO product (name, type, price) VALUES ('Adobe Photoshop (1 Year)', 'Software', 3100000);
INSERT INTO product (name, type, price) VALUES ('Microsoft Office 365 Personal', 'Software', 950000);
INSERT INTO product (name, type, price) VALUES ('Final Cut Pro', 'Software', 4500000);
INSERT INTO product (name, type, price) VALUES ('Sketch App', 'Software', 1500000);
INSERT INTO product (name, type, price) VALUES ('VMware Fusion', 'Software', 2200000);
INSERT INTO product (name, type, price) VALUES ('1Password Family Plan', 'Software', 600000);
INSERT INTO product (name, type, price) VALUES ('Tableau Desktop', 'Software', 10500000);
INSERT INTO product (name, type, price) VALUES ('AutoCAD LT', 'Software', 6800000);
INSERT INTO product (name, type, price) VALUES ('Ableton Live Suite', 'Software', 11000000);
INSERT INTO product (name, type, price) VALUES ('Dell UltraSharp U2723QE', 'Monitor', 8500000);
INSERT INTO product (name, type, price) VALUES ('LG 34" Ultrawide 34WK95U', 'Monitor', 15000000);
INSERT INTO product (name, type, price) VALUES ('Samsung Odyssey G9', 'Monitor', 22000000);
INSERT INTO product (name, type, price) VALUES ('BenQ PD3200U 32"', 'Monitor', 11000000);
INSERT INTO product (name, type, price) VALUES ('Asus ProArt PA279CV', 'Monitor', 7800000);
INSERT INTO product (name, type, price) VALUES ('HP Z27k G3 4K', 'Monitor', 8200000);
INSERT INTO product (name, type, price) VALUES ('ViewSonic VP2785-4K', 'Monitor', 9500000);
INSERT INTO product (name, type, price) VALUES ('Gigabyte M32U', 'Monitor', 12500000);
INSERT INTO product (name, type, price) VALUES ('Apple Studio Display', 'Monitor', 25000000);
INSERT INTO product (name, type, price) VALUES ('Acer Predator XB273K', 'Monitor', 13000000);
INSERT INTO product (name,type, price) VALUES ('Macbook Air M2', 'Laptop', 17000000);
INSERT INTO product (name,type, price) VALUES ('iPhone 15 Standard', 'Smartphone', 15000000);
INSERT INTO product (name,type, price) VALUES ('Effective Java', 'Book', 400000);
INSERT INTO product (name,type, price) VALUES ('Corsair K70 RGB Keyboard', 'Accessory', 2100000);
INSERT INTO product (name,type, price) VALUES ('Sublime Text License', 'Software', 1200000);
INSERT INTO product (name,type, price) VALUES ('LG 27GP850-B', 'Monitor', 6500000);
INSERT INTO product (name,type, price) VALUES ('Lenovo Legion 5', 'Laptop', 19500000);
INSERT INTO product (name,type, price) VALUES ('Samsung Galaxy Z Fold 5', 'Smartphone', 29000000);
INSERT INTO product (name,type, price) VALUES ('Grokking Algorithms', 'Book', 375000);
INSERT INTO product (name,type, price) VALUES ('Razer DeathAdder V3 Mouse', 'Accessory', 950000);
INSERT INTO product (name,type, price) VALUES ('JetBrains All Products Pack', 'Software', 9800000);
INSERT INTO product (name,type, price) VALUES ('Dell Alienware AW3423DW', 'Monitor', 18000000);
INSERT INTO product (name,type, price) VALUES ('HP Omen 16', 'Laptop', 24000000);
INSERT INTO product (name,type, price) VALUES ('Google Pixel Fold', 'Smartphone', 26000000);
INSERT INTO product (name,type, price) VALUES ('Building Microservices', 'Book', 415000);
INSERT INTO product (name,type, price) VALUES ('Focusrite Scarlett 2i2', 'Accessory', 2500000);
INSERT INTO product (name,type, price) VALUES ('Windows 11 Pro', 'Software', 3000000);
INSERT INTO product (name,type, price) VALUES ('Samsung M8 Smart Monitor', 'Monitor', 9000000);
INSERT INTO product (name,type, price) VALUES ('MSI Stealth 15M', 'Laptop', 21000000);
INSERT INTO product (name,type, price) VALUES ('Vivo X100 Pro', 'Smartphone', 16000000);
INSERT INTO product (name,type, price) VALUES ('Fundamentals of Data Engineering', 'Book', 600000);
INSERT INTO product (name,type, price) VALUES ('Elgato Stream Deck', 'Accessory', 2300000);
INSERT INTO product (name,type, price) VALUES ('Figma Pro (1 Year)', 'Software', 1800000);
INSERT INTO product (name,type, price) VALUES ('BenQ EX2710Q', 'Monitor', 7200000);
INSERT INTO product (name,type, price) VALUES ('Acer Predator Helios 300', 'Laptop', 26000000);
INSERT INTO product (name,type, price) VALUES ('Realme GT 5', 'Smartphone', 9000000);
INSERT INTO product (name,type, price) VALUES ('The Phoenix Project', 'Book', 360000);
INSERT INTO product (name,type, price) VALUES ('CalDigit TS4 Thunderbolt Dock', 'Accessory', 6000000);
INSERT INTO product (name,type, price) VALUES ('Affinity Designer 2', 'Software', 1000000);
INSERT INTO product (name,type, price) VALUES ('AOC 24G2', 'Monitor', 2800000);
INSERT INTO product (name,type, price) VALUES ('Framework Laptop 13', 'Laptop', 20000000);
INSERT INTO product (name,type, price) VALUES ('Honor Magic6 Pro', 'Smartphone', 15500000);
INSERT INTO product (name,type, price) VALUES ('System Design Interview', 'Book', 520000);
INSERT INTO product (name,type, price) VALUES ('SteelSeries Arctis Nova Pro', 'Accessory', 5000000);
INSERT INTO product (name,type, price) VALUES ('Docker Desktop Pro (1 Year)', 'Software', 850000);
INSERT INTO product (name,type, price) VALUES ('MSI Optix MAG274QRF-QD', 'Monitor', 8100000);
INSERT INTO product (name,type, price) VALUES ('ThinkPad P1 Gen 6', 'Laptop', 45000000);
INSERT INTO product (name,type, price) VALUES ('iPhone SE (2022)', 'Smartphone', 7500000);
INSERT INTO product (name,type, price) VALUES ('Release It!', 'Book', 425000);
INSERT INTO product (name,type, price) VALUES ('Logitech MX Keys', 'Accessory', 1600000);
INSERT INTO product (name,type, price) VALUES ('Postman Pro (1 Year)', 'Software', 2100000);
INSERT INTO product (name,type, price) VALUES ('Corsair XENEON 27QHD240', 'Monitor', 14000000);
INSERT INTO product (name,type, price) VALUES ('Gigabyte AERO 16', 'Laptop', 33000000);
INSERT INTO product (name,type, price) VALUES ('Samsung Galaxy A55', 'Smartphone', 6500000);
INSERT INTO product (name,type, price) VALUES ('Database Internals', 'Book', 580000);
INSERT INTO product (name,type, price) VALUES ('Shure MV7 Microphone', 'Accessory', 3800000);
INSERT INTO product (name,type, price) VALUES ('ZBrush', 'Software', 13000000);
INSERT INTO product (name,type, price) VALUES ('ViewSonic XG2431', 'Monitor', 4500000);
INSERT INTO product (name,type, price) VALUES ('Dell XPS 17', 'Laptop', 41000000);
INSERT INTO product (name,type, price) VALUES ('Poco F6 Pro', 'Smartphone', 7800000);
INSERT INTO product (name,type, price) VALUES ('Refactoring: Improving the Design of Existing Code', 'Book', 510000);
INSERT INTO product (name,type, price) VALUES ('Apple Airpods Pro 2', 'Accessory', 3500000);
INSERT INTO product (name,type, price) VALUES ('Parallels Desktop', 'Software', 1400000);
INSERT INTO product (name,type, price) VALUES ('Gigabyte G27Q', 'Monitor', 4900000);
INSERT INTO product (name,type, price) VALUES ('Asus Zenbook Duo', 'Laptop', 29000000);
INSERT INTO product (name,type, price) VALUES ('Infinix Note 40 Pro', 'Smartphone', 3500000);
INSERT INTO product (name,type, price) VALUES ('Code Complete 2', 'Book', 620000);
INSERT INTO product (name,type, price) VALUES ('Logitech Litra Glow', 'Accessory', 900000);
INSERT INTO product (name,type, price) VALUES ('DaVinci Resolve Studio', 'Software', 4800000);
INSERT INTO product (name,type, price) VALUES ('Asus TUF Gaming VG27AQ', 'Monitor', 5800000);
INSERT INTO product (name,type, price) VALUES ('Lenovo Yoga Slim 7', 'Laptop', 16000000);
INSERT INTO product (name,type, price) VALUES ('Redmi Note 13 Pro', 'Smartphone', 4200000);
INSERT INTO product (name,type, price) VALUES ('The Mythical Man-Month', 'Book', 330000);
INSERT INTO product (name,type, price) VALUES ('YubiKey 5C NFC', 'Accessory', 850000);
INSERT INTO product (name,type, price) VALUES ('Slack Pro (1 Year/User)', 'Software', 1250000);
INSERT INTO product (name,type, price) VALUES ('LG 32GQ950-B', 'Monitor', 16000000);